name: deploy tencent

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
     - uses: actions/setup-node@v3
       with:
          node-version: '18'
          
     - uses: actions/checkout@v3
     - uses: bahmutov/npm-install@v1
       with:
          working-directory: ./

     - run: yarn build
     - run: yarn export
